# Generated by Django 4.1 on 2022-10-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='descripteion',
            new_name='description',
        ),
    ]
